# Generated by Django 5.2.4 on 2025-08-23 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Publication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("headline", models.CharField(max_length=30, verbose_name="Заголовок")),
                ("contents", models.TextField(blank=True, null=True)),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="images/",
                        verbose_name="Фотография",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("published", models.BooleanField(default=True)),
                ("number_of_views", models.IntegerField(default=0)),
            ],
            options={
                "verbose_name": "Публикация",
                "verbose_name_plural": "Публикации",
            },
        ),
    ]
