# Generated by Django 5.2.4 on 2025-08-24 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="publication",
            name="number_of_views",
            field=models.IntegerField(default=0, verbose_name="Счетчик просмотров"),
        ),
    ]
