# Generated by Django 5.2.4 on 2025-08-24 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_alter_publication_number_of_views"),
    ]

    operations = [
        migrations.AlterField(
            model_name="publication",
            name="published",
            field=models.BooleanField(default=False),
        ),
    ]
